#!/usr/bin/env bash
# install nginx on your web server
# Nginx should be listening on port 80

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx start
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
