#!/usr/bin/env bash
# install nginx on your web server
# Nginx should be listening on port 80

sudo apt-get update
sudo apt-get -y install nginx
echo "Hello World" > /var/www/html/index.html
sudo service nginx restart
