#!/usr/bin/env bash
# blablabla
sudo apt-get -y update
sudo apt-get -y install nginx
sudo chmod 777 /var/www/html/ -R
echo "Hello World" > /var/www/html/index.html
sudo chmod 777 /etc/nginx/sites-enabled/default /etc/nginx/sites-enabled/
sudo sed -i "/listen 80 default_server;/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default
sudo service nginx restart
