#!/usr/bin/env bash
# Run nginx as nginx user
pkill apache2
chown nginx:nginx /etc/nginx/nginx.conf
chmod 700 /etc/nginx/nginx.conf
sudo sed -i 's/80.*/8080/' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
